name: Streamlit Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install gspread google-auth

    - name: Write credentials to file
      env:
        SERVICE_CREDENTIAL: ${{ secrets.SERVICE_CREDENTIAL }}  # Use the secret
      run: |
        echo "$SERVICE_CREDENTIAL" > service_credentials.json  # Write the secret to a file
        cat service_credentials.json  # Debug: Print the file contents to verify

    - name: Run Streamlit app
      run: |
        streamlit run streamlit_app.py
