name: Alteryx Workflow Scheduler

on:
  schedule:
    - cron: '5 * * * *'  # Schedule to run daily at 6:05 AM UTC
  workflow_dispatch:     # Allows manual triggers as well

jobs:
  run-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SERVICE_CREDENTIAL }}  # Add other secrets as needed
        run: |
          python streamlit_app.py
