name: Sync Data from Google Drive

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every 1 minute (minimum interval for GitHub Actions)
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Download Data from Google Drive
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  # Store credentials.json as a secret
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          python scripts/download_from_drive.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/
          git commit -m "Automated data update from Google Drive"
          git push
